working_directory = "/Users/netrolite/Documents"

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[font]
size = 16.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }

[keyboard]
bindings = [
  { key = "Down", mods = "Command", action = "ScrollToBottom" },
  { key = "Up", mods = "Command", action = "ScrollToTop" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
